server:
     port: 9193
   
spring :
   application: 
      name : EMPLOYE-SERVICE
   datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/varma
        username: root
        password: Narendra@87
   jpa:
       hibernate.ddl-auto: update
       generate-ddl: true
       show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost